name: hello
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1




environment:
  sdk: ">=2.15.1 <3.0.0"




dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Splash Screen library
  splash_screen_view: ^3.0.0
  # Google Fonts
  google_fonts: ^2.2.0
  # Fire Base
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  cloud_firestore: ^3.1.5
  firebase_storage: ^10.2.5
  # Provider
  provider: ^5.0.0
  # Shared Preferences
  shared_preferences: ^2.0.11
  # Toast
  fluttertoast: ^8.0.8
  # Setting UI
  flutter_settings_ui: ^2.0.1
  # Image Picker
  file_picker: ^4.3.0
  cached_network_image: ^3.2.0
  # Language
  easy_localization: ^3.0.0
  #Loading
  flutter_spinkit: ^5.1.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0




flutter:
  uses-material-design: true
  assets:
    - asset/image/SplashPage/
    - asset/image/home/
    - asset/image/Custem/
    - asset/image/Requst/
    - asset/image/admin/
    - asset/image/Drawer/
    - asset/image/lang/
    - asset/Lang/
